// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxxSZ0f2kFWuSL9NA5Q3EoYjjS28ihyIo',
    appId: '1:789625081686:web:a458005e80f0563fc190f7',
    messagingSenderId: '789625081686',
    projectId: 'asap-route',
    authDomain: 'asap-route.firebaseapp.com',
    storageBucket: 'asap-route.appspot.com',
    measurementId: 'G-FWG7Y6GLLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNdDRrvnAwqD5hjkryAItRCtFXAHKtMo',
    appId: '1:789625081686:android:1ce0e2698da7940fc190f7',
    messagingSenderId: '789625081686',
    projectId: 'asap-route',
    storageBucket: 'asap-route.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYkNq6wqYvhD44xtUTN1FD0tjTxOVx6w',
    appId: '1:789625081686:ios:b41ded566d3b37edc190f7',
    messagingSenderId: '789625081686',
    projectId: 'asap-route',
    storageBucket: 'asap-route.appspot.com',
    androidClientId: '789625081686-352unph5lpallne2d5p2uh0dhe9jp6kv.apps.googleusercontent.com',
    iosClientId: '789625081686-3tqvqf67gsktvubb0qij6kjm03jfsbqd.apps.googleusercontent.com',
    iosBundleId: 'com.asap.route.route',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaYkNq6wqYvhD44xtUTN1FD0tjTxOVx6w',
    appId: '1:789625081686:ios:b41ded566d3b37edc190f7',
    messagingSenderId: '789625081686',
    projectId: 'asap-route',
    storageBucket: 'asap-route.appspot.com',
    androidClientId: '789625081686-352unph5lpallne2d5p2uh0dhe9jp6kv.apps.googleusercontent.com',
    iosClientId: '789625081686-3tqvqf67gsktvubb0qij6kjm03jfsbqd.apps.googleusercontent.com',
    iosBundleId: 'com.asap.route.route',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxxSZ0f2kFWuSL9NA5Q3EoYjjS28ihyIo',
    appId: '1:789625081686:web:dcbabb85d66c70e6c190f7',
    messagingSenderId: '789625081686',
    projectId: 'asap-route',
    authDomain: 'asap-route.firebaseapp.com',
    storageBucket: 'asap-route.appspot.com',
    measurementId: 'G-E8FP950PV9',
  );
}
